# Generated by Django 3.0.7 on 2020-06-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date_posted',
            new_name='date',
        ),
    ]
