# Generated by Django 3.0.7 on 2020-06-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200603_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
